// <auto-generated />
using System;
using KursyWalutNBP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KursyWalutNBP.Migrations
{
    [DbContext(typeof(ExchangeRateContext))]
    partial class ExchangeRateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KursyWalutNBP.Models.RateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aud")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Bgn")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Brl")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Cad")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Chf")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Clp")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Cny")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Czk")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Dkk")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Eur")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Gbp")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Hkd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Huf")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Idr")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Ils")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Inr")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Isk")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Jpy")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Krw")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Mxn")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Myr")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Nok")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Nzd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Php")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Ron")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Sek")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Sgd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Thb")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Try")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Uah")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Usd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Xdr")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
